name: Daily Crawl & Deploy
on:
  schedule:
    - cron: '30 2 * * *'  # 每天北京时间 10:30 运行
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 拉取代码
        uses: actions/checkout@v5

      - name: 设置 Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: |
          pip install requests beautifulsoup4

      - name: 运行爬虫
        run: python crawler.py

      - name: 提交更新
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.html
          git commit -m "自动更新 $(date +'%Y-%m-%d') 链接" || exit 0
          git push
